# coding: utf-8

"""
    Search API

    For existing users using the api.skypicker.com endpoint:\\ You need to have an affiliate (partner) ID. This ID is used across Kiwi.com services to distinguish between partners. In this API, for all endpoints, you need to specify it in query parameter `partner`.  For new users of the Kiwi.com APIs:\\ Please register to our Tequila portal at [tequila.kiwi.com](https://tequila.kiwi.com/) to get your unique API key and use the new API there.  This API provides several options how to search for itineraries. At the moment there are different type of itineraries and different endpoints how to search for them. For oneway and roundtrip itineraries /flights endpoint need to be used. If you want to search for itineraries with multiple stops and you know exactly in which order you want them, then use our multicity searching which is available on /flights/multicity endpoint. Finally if you want to search for itineraries where you know the start and end of you journey and you know all the stops, but you don't mind in which order then you can use our Nomad searching which is available on /traveling_salesman endpoint.  Response from all endpoints will contain a list of itineraries, where each itinerary contain a link leading directly to Kiwi.com booking page where the user can book the specified flight. Each itinerary will also contain booking token which is needed in [Booking API](https://docs.kiwi.com/#header-booking-api).  Please note that all parameters marked as \"Deprecated\" are still accepted, although later they will be decommissioned. Some of them will be decommissioned completely and some of them can be replaced with other more powerful parameters. More information can be found in the description of the actual parameter.  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Body3Via(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'locations': 'Locations',
        'date_range': 'DateRange',
        'nights_range': 'NomadNightsRange'
    }

    attribute_map = {
        'locations': 'locations',
        'date_range': 'date_range',
        'nights_range': 'nights_range'
    }

    def __init__(self, locations=None, date_range=None, nights_range=None):  # noqa: E501
        """Body3Via - a model defined in Swagger"""  # noqa: E501
        self._locations = None
        self._date_range = None
        self._nights_range = None
        self.discriminator = None
        self.locations = locations
        if date_range is not None:
            self.date_range = date_range
        if nights_range is not None:
            self.nights_range = nights_range

    @property
    def locations(self):
        """Gets the locations of this Body3Via.  # noqa: E501


        :return: The locations of this Body3Via.  # noqa: E501
        :rtype: Locations
        """
        return self._locations

    @locations.setter
    def locations(self, locations):
        """Sets the locations of this Body3Via.


        :param locations: The locations of this Body3Via.  # noqa: E501
        :type: Locations
        """
        if locations is None:
            raise ValueError("Invalid value for `locations`, must not be `None`")  # noqa: E501

        self._locations = locations

    @property
    def date_range(self):
        """Gets the date_range of this Body3Via.  # noqa: E501


        :return: The date_range of this Body3Via.  # noqa: E501
        :rtype: DateRange
        """
        return self._date_range

    @date_range.setter
    def date_range(self, date_range):
        """Sets the date_range of this Body3Via.


        :param date_range: The date_range of this Body3Via.  # noqa: E501
        :type: DateRange
        """

        self._date_range = date_range

    @property
    def nights_range(self):
        """Gets the nights_range of this Body3Via.  # noqa: E501


        :return: The nights_range of this Body3Via.  # noqa: E501
        :rtype: NomadNightsRange
        """
        return self._nights_range

    @nights_range.setter
    def nights_range(self, nights_range):
        """Sets the nights_range of this Body3Via.


        :param nights_range: The nights_range of this Body3Via.  # noqa: E501
        :type: NomadNightsRange
        """

        self._nights_range = nights_range

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body3Via, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body3Via):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
